distributor:
  enable: true
  undoneTaskLimitPerInterpolater: 6
  totalTaskGeneratorThreadNumber: 1
  totalTaskUpdaterThreadNumber: 1
  timeoutMinutes: 5

interpolater:
  enable: true
  concurrentNumber: 8
  distributorURL: http://localhost:${server.port}
  callbackHttpEnum: http
  cellSize: 30
  maxInvalidNum: 3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctpf2
    username: postgres
    password: w.w1w+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  aop:
    auto: true