distributor:
  enable: true
  undoneTaskLimitPerInterpolater: 10
  currentNumber: 4
  timeoutMinutes: 15

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctpf
    username: postgres
    password: w.w1w+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  aop:
    auto: true