distributor:
  enable: true
  totalTaskGeneratorThreadNumber: 10
  totalTaskUpdaterThreadNumber: 1
  totalTaskDistributorPostThreadNumber: 16
  taskStoreMaxCount: 50
  timeoutMinutes: 5
  filePath: ${logging.file.path}/data.binary

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctpf2
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  aop:
    auto: true