distributor:
  enable: true
  totalTaskGeneratorThreadNumber: 6
  totalTaskUpdaterThreadNumber: 4
  totalTaskDistributorPostThreadNumber: 20
  taskStoreMaxCount: 50
  timeoutMinutes: 5

interpolater:
  enable: true
  concurrentNumber: 8
  distributorURL: http://localhost:${server.port}
  callbackHttpEnum: http
  cellSize: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctpf2
    username: postgres
    password: w.w1w+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  aop:
    auto: true