distributor:
  enable: true
  undoneTaskLimitPerInterpolater: 10
  currentNumber: 1
  timeoutMinutes: 15

interpolater:
  enable: true
  currentNumber: 1
  distributorURL: http://localhost:${server.port}
  callbackHttpEnum: http
  cellSize: 300
  maxInvalidNum: 3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctpf2
    username: postgres
    password: w.w1w+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  aop:
    auto: true