distributor:
  enable: true
  totalTaskGeneratorThreadNumber: 1
  totalTaskUpdaterThreadNumber: 1
  totalTaskDistributorPostThreadNumber: 1
  taskStoreMaxCount: 10
  timeoutMinutes: 5
  filePath: ${logging.file.path}/data.binary

interpolater:
  enable: true
  concurrentNumber: 8
  distributorURL: http://localhost:${server.port}
  callbackHttpEnum: http
  cellSize: 30
  taskFactor: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctpf2
    username: postgres
    password: w.w1w+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  aop:
    auto: true